version: "3.8"

services:
    uptime-kuma:
        image: louislam/uptime-kuma:latest
        container_name: uptime-kuma
        volumes:
            - kuma-data:/app/data
        ports:
            - "3001:3001"
        networks:
            - proxy-network
        restart: unless-stopped

volumes:
    kuma-data:

networks:
    proxy-network:
        external: true
